import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css'; // Global styles
import { motion } from 'framer-motion'; // To use motion effects in the layout if needed


const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {children} {/* This renders your page.js */}
      </body>
    </html>
  );
}
